import puppeteer from 'puppeteer-core'
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--no-sandbox', '--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist'] })
const page = await browser.newPage()
await page.setViewport({ width: 1600, height: 1000 })
page.on('pageerror', (e) => console.log('PAGEERROR', e.stack))
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('404')) console.log('ERR', m.text().slice(0, 300)) })
await page.goto('http://127.0.0.1:5218/', { waitUntil: 'domcontentloaded' })
await page.waitForFunction('window.__gsReady === true', { timeout: 90000 })
await page.evaluate(() => { window.__gs.settings.pathTracing = false; window.__gs.toggleFold() })
await new Promise((r) => setTimeout(r, 1300))
await page.screenshot({ path: 'shots/fold_mid.png' })
await new Promise((r) => setTimeout(r, 2500))
await page.screenshot({ path: 'shots/fold_end.png' })
await page.evaluate(() => window.__gs.controls.setLookAt(-0.6, 1.6, 2.2, -0.15, 0.4, -0.1, false))
await new Promise((r) => setTimeout(r, 1500))
await page.screenshot({ path: 'shots/fold_top.png' })
await page.evaluate(() => { window.__gs.toggleFold() })
await new Promise((r) => setTimeout(r, 4000))
await page.evaluate(() => { window.__gs.view('tre4', false); window.__gs.toggleSpin() })
await new Promise((r) => setTimeout(r, 2500))
await page.screenshot({ path: 'shots/spin.png' })
await browser.close()
