import puppeteer from 'puppeteer-core'
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--no-sandbox', '--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist'] })
const page = await browser.newPage()
await page.setViewport({ width: 1600, height: 1000 })
page.on('pageerror', (e) => console.log('PAGEERROR ' + e.stack))
await page.goto('http://127.0.0.1:5218/', { waitUntil: 'domcontentloaded' })
await page.waitForFunction('window.__gsReady === true', { timeout: 90000 })
await new Promise((r) => setTimeout(r, 1200))
const tabs = await page.$$('.tab')
await tabs[1].click()
await new Promise((r) => setTimeout(r, 300))
const envs = await page.$$('.env')
await envs[1].click()
await new Promise((r) => setTimeout(r, 2500))
await page.evaluate(() => { window.__gs.settings.pathTracing = false })
await page.keyboard.press('?')
await new Promise((r) => setTimeout(r, 1200))
await page.screenshot({ path: 'shots/dark_ui.png' })
await browser.close()
