import puppeteer from 'puppeteer-core'
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--no-sandbox', '--use-angle=metal', '--enable-gpu'] })
const page = await browser.newPage()
await page.setViewport({ width: 1200, height: 750 })
const errs = []
page.on('pageerror', (e) => errs.push(e.message))
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text().slice(0, 200)) })
await page.goto('http://127.0.0.1:5218/', { waitUntil: 'domcontentloaded' })
await page.waitForFunction('window.__gsReady === true', { timeout: 120000 })
await page.addStyleTag({ content: '.panel,.toolbar,.status,.hint,.wordmark{display:none!important}' })
await page.evaluate(async () => { const s = window.__gs; s.settings.pathTracing = false; await s.setAmbient({ set: 'citta', citta: 'pomeriggio' }); s.view('tre4', false); s.toggleFold() })
await new Promise((r) => setTimeout(r, 1500))
await page.screenshot({ path: 'shots/sets/anim_fold_mid.png' })
await new Promise((r) => setTimeout(r, 2500))
await page.screenshot({ path: 'shots/sets/anim_folded.png' })
await page.evaluate(() => { window.__gs.toggleFold() })
await new Promise((r) => setTimeout(r, 3500))
await page.evaluate(() => { window.__gs.toggleSpin() })
await new Promise((r) => setTimeout(r, 1500))
const fm = await page.evaluate(() => window.__gs.frameMs)
await page.screenshot({ path: 'shots/sets/anim_spin.png' })
await page.evaluate(() => { window.__gs.toggleSpin() })
console.log(JSON.stringify({ frameMsSpinning: +fm.toFixed(1), errs }))
await browser.close()
